{{- define "common-chart.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common-chart.fullname" $ }}-{{ .name }}
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
