{{- range .Values.secrets }}
{{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common-chart.fullname" $ }}-{{ .name }}
type: Opaque
data:
{{- range $key, $value := .data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
